version: '3'

services:
  app: 
    build: .
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app

  db: 
    image: bitnami/mongodb:5.0.17
    volumes: 
      - mongodb_data:/bitnami/mongodb
    ## Poderia rodar na máquina, porém teria que expor a porta 
    ## e mudar DATABASE_URL de db para localhost 
    # ports:
    #   - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: vehicle_tracking_server
  
  redis:
    image: redis:7.0.8-alpine
      
volumes: 
  mongodb_data:
    driver: local